import Footer from '@/components/footer'
import Header from '@/components/header'
import './globals.scss'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <div className='children'>
        {children}
        </div>
        {/* {children} */}
        <Footer/>
        </body>
    </html>
  )
}
